menu:
  首页: /
  归档: /archives
  关于: /about
  工具: /tools
  

widgets:
- category
- intro
- tagcloud
- blogroll
- weibo

excerpt_link: 阅读全文

fancybox: true
google_analytics: true
baidu_analytics: true
rss: /atom.xml
